const gateway = {
    "Gateway.Login.Req": "LoginReq",
    "Gateway.Login.Resp": "LoginResp",
    "Gateway.RoomJoin.Req": "RoomJoinReq",
    "Gateway.RoomJoin.Resp": "RoomJoinResp",
    "Gateway.RoomJoin.Up": "RoomJoinNotifyUp",
    "Gateway.RoomJoin.Notify": "RoomJoinNotify",
    "Gateway.RoomLeave.Up": "RoomLeaveReq",
    "Gateway.Chat.Up": "ChatUp",
    "Gateway.Chat.Notify": "ChatNotify",
    "Gateway.Gift.Up": "GiftUp",
    "Gateway.Gift.Notify": "GiftNotify",
    "Gateway.Bag.Up": "BagUp",
    "Gateway.Bag.Notify": "BagNotify",
    "Gateway.Zan.Up": "ZanUp",
    "Gateway.Zan.Notify": "ZanNotify",
    "Gateway.Manager.Notify": "ManagerNotify",
    "Gateway.RoomUpdate.Notify": "RoomUpdateNotify",
    "Gateway.Guard.Notify": "RoomGuardNotify",
    "Gateway.AnchorLiveStatus.Notify": "AnchorLiveStatusNotify",
    "Gateway.Shared.Notify": "SharedNotify",
    "Gateway.Followed.Notify": "FollowedNotify",
    "Gateway.RedEnvelope.Notify": "RedEnvelopeNotify",
    "Gateway.UserAttr.Notify": "UserAttrNotify",
    "Gateway.UserLevelUp.Notify": "UserLevelUpNotify",
    "Gateway.Kickout.Notify": "KickoutNotify",
    "Gateway.Banner.Notify": "BannerNotify",
    "Gateway.OfficialLiveStatus.Notify": "OfficialLiveStatusNotify",
    "Gateway.OfficialLiveLike.Up": "OfficialLiveLikeUp",
    "Gateway.OfficialLiveLike.Notify": "OfficialLiveLikeNotify",
    "Gateway.Award.Notify": "ChallengeAward",
    "Gateway.GlobalMsg.Notify": "GlobalMsg",
    "Gateway.HonorLevelUp.Notify": "HonorLevelUp",
    "Gateway.FriendStatus.Notify": "FriendStatus",
    "Gateway.RectifyRoom.Notify": "RectifyRoomNotify",
    "Gateway.Bomb.Notify": "BombNotify"
}

module.exports = gateway